### ISSUE TITLE
Feature request : Add reading IQ from stdin

### ISSUE THREAD

**Issue by MinNyaLya** [juerec/decoders#1]
Hi! Great piece of decoder work here. Would you be able to add the possibility to read from Stdin, so it would be possible to pipe the IQ output from rtf_fm directly into the decoder. It would save a lot of space on small devices such as RPI, not needing to have a huge 10min long sample file stored.

**Comment by juerec** [comment]
Hi,

 

I'am working on stdin input. Give me a short count of days for testing.

 
 

Gesendet: Dienstag, 26. Mai 2020 um 10:00 Uhr
Von: "MinNyaLya" <notifications@github.com>
An: "juerec/decoders" <decoders@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [juerec/decoders] Feature request : Add reading IQ from stdin (#1)


 

Hi! Great piece of decoder work here. Would you be able to add the possibility to read from Stdin, so it would be possible to pipe the IQ output from rtf_fm directly into the decoder. It would save a lot of space on small devices such as RPI, not needing to have a huge 10min long sample file stored.

**Comment by MinNyaLya** [comment]
Awesome, let me know and I can try it out!

**Comment by juerec** [comment]
Inpout from stdin is committed

**Comment by juerec** [comment]
It's online
 

Gesendet: Donnerstag, 04. Juni 2020 um 10:03 Uhr
Von: "MinNyaLya" <notifications@github.com>
An: "juerec/decoders" <decoders@noreply.github.com>
Cc: "juerec" <pc.navtex@web.de>, "Comment" <comment@noreply.github.com>
Betreff: Re: [juerec/decoders] Feature request : Add reading IQ from stdin (#1)


 
Awesome, let me know and I can try it out!

**Comment by MinNyaLya** [comment]
Thanks! I had two errors when compiling : In main.cpp isSampleRate is used
in a if() and does not exists and in Logger.cpp there was reference to
nullptr that failed.

**Comment by MinNyaLya** [comment]
And a misspelling "sdtin" instead of "stdin"

**Comment by juerec** [comment]
A update is pushed to github.

If the problem with the logger consists again, pleas give me a little more detailed info.

 

Thanks!

 
 

Gesendet: Freitag, 05. Juni 2020 um 11:57 Uhr
Von: "MinNyaLya" <notifications@github.com>
An: "juerec/decoders" <decoders@noreply.github.com>
Cc: "juerec" <pc.navtex@web.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [juerec/decoders] Feature request : Add reading IQ from stdin (#1)


 
And a misspelling "sdtin" instead of "stdin"

**Comment by MinNyaLya** [comment]
Hi,

This is the error I get:

*DecoderIO.cpp:50:103: error: 'nullptr' was not declared in this scope*
*         logger.error("DecoderIO::init()", __LINE__, " cannot open wave
file: \"%s\"\n", DeviceName == nullptr ? "NULL" : DeviceName);*

Looks like you are missing "-std=gnu++0x" in the g++ parameters in the
Makefile.

*cpp_flags=-fno-exceptions -fno-rtti -O0 $(c_flags) -DNO_THREADS
-std=gnu++0x*

/Göran

**Comment by juerec** [comment]
Hi

 

where do you define -std=gnu++0x* ? The Makefile does it not.
 

It seems your "-std=gnu++0x" is the problem. "nullptr" is defined in C++ since C++11 (?).

 

 
 

Gesendet: Montag, 08. Juni 2020 um 13:05 Uhr
Von: "MinNyaLya" <notifications@github.com>
An: "juerec/decoders" <decoders@noreply.github.com>
Cc: "juerec" <pc.navtex@web.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [juerec/decoders] Feature request : Add reading IQ from stdin (#1)


 
Hi,

This is the error I get:

*DecoderIO.cpp:50:103: error: 'nullptr' was not declared in this scope*
* logger.error("DecoderIO::init()", __LINE__, " cannot open wave
file: \"%s\"\n", DeviceName == nullptr ? "NULL" : DeviceName);*

Looks like you are missing "-std=gnu++0x" in the g++ parameters in the
Makefile.

*cpp_flags=-fno-exceptions -fno-rtti -O0 $(c_flags) -DNO_THREADS
-std=gnu++0x*

/Göran

**Comment by MinNyaLya** [comment]
Hi,

Sorry for being unclear. Im compiling on a RapsberryPI and (g++) gcc
version 4.9.2 (Raspbian 4.9.2-10) it should support nullprt from that
version.
But still I have to add "-std=gnu++0x" into the Makefile so the compiler
accepts the "nullptr" in the code.

Maybe this is more of a problem on my environment.

Thanks!
/Göran
